Storage:
  type: JSON # JSON, SQLite, MySQL, yml
Account:
  Display: EusMC # 包含在二维码内服务器的名称，可自定义，APP 扫描后会显示该名称
Plugins:
  GeoIP: false # 布尔值，开启 GeoIP 地址检测，根据地址变动自动启用进服验证
  GeoIP-lib: /GeoIP/GeoIP2-City.mmdb # 填入 GeoIP 的数据库地址，此为示例